# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 20:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_auto_20161103_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friend_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friend_to', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friend',
            name='user_to',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
