# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-19 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0004_friend_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='seen',
        ),
    ]
